// Generated by Gemini - reviewed by [Tu Nombre] - 2026-03-28
const convertCurrency = async (req, res) => {
  try {
    const { from, to, amount } = req.query;

    // 1. Validación de tipos y presencia
    if (!from || !to || !amount) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'Missing parameters: from, to, and amount are required.'
      });
    }

    const numericAmount = parseFloat(amount);
    if (isNaN(numericAmount) || numericAmount <= 0) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'Invalid amount: Must be a positive number.'
      });
    }

    // 2. Lógica de negocio (Mock de tasa de cambio)
    const mockRate = 0.92; // Ejemplo USD a EUR
    const result = (numericAmount * mockRate).toFixed(2);

    // 3. Respuesta profesional
    return res.status(200).json({
      success: true,
      data: {
        from: from.toUpperCase(),
        to: to.toUpperCase(),
        originalAmount: numericAmount,
        convertedAmount: parseFloat(result),
        rate: mockRate
      },
      error: null
    });

  } catch (err) {
    return res.status(500).json({
      success: false,
      data: null,
      error: 'Internal Server Error'
    });
  }
};

module.exports = { convertCurrency };