// Generated by Gemini - reviewed by [Tu Nombre] - 2026-03-28
const QRCode = require('qrcode');

/**
 * POST /qr
 * Genera un código QR a partir de un texto proporcionado en el body.
 */
const generateQR = async (req, res) => {
  try {
    const { text } = req.body;

    // 1. Validación de entrada: ¿Existe el campo y no es solo espacios?
    if (!text || typeof text !== 'string' || text.trim().length === 0) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'Invalid input: "text" field is required and cannot be empty.'
      });
    }

    // 2. Limitación de seguridad (Evitar payloads masivos)
    if (text.length > 2000) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'Payload too large: Max 2000 characters allowed.'
      });
    }

    // 3. Generación del QR (se obtiene como DataURL/Base64)
    const qrDataUrl = await QRCode.toDataURL(text);

    // 4. Respuesta exitosa
    return res.status(200).json({
      success: true,
      data: qrDataUrl,
      error: null
    });

  } catch (err) {
    // 5. Gestión de errores del servidor
    console.error(`[Error Generating QR]: ${err.message}`);
    return res.status(500).json({
      success: false,
      data: null,
      error: 'Internal Server Error: Failed to generate QR code.'
    });
  }
};

module.exports = { generateQR };