// Generated by Gemini - reviewed by [Tu Nombre] - 2026-03-28
const { expect } = require('chai');
const { generateQR } = require('../../src/api/handler');

// Mock simple del objeto response de Express
const mockResponse = () => {
  const res = {};
  res.status = (code) => {
    res.statusCode = code;
    return res;
  };
  res.json = (data) => {
    res.body = data;
    return res;
  };
  return res;
};

describe('QR Handler Unit Tests', () => {
  
  it('Should return 200 and a valid Base64 string for valid input (Happy Path)', async () => {
    const req = { body: { text: 'https://github.com/javtl/qr-app' } };
    const res = mockResponse();

    await generateQR(req, res);

    expect(res.statusCode).to.equal(200);
    expect(res.body.success).to.be.true;
    expect(res.body.data).to.contain('data:image/png;base64,');
  });

  it('Should return 400 error for empty text input', async () => {
    const req = { body: { text: '' } };
    const res = mockResponse();

    await generateQR(req, res);

    expect(res.statusCode).to.equal(400);
    expect(res.body.success).to.be.false;
    expect(res.body.error).to.equal('Invalid input: "text" field is required and cannot be empty.');
  });
});